# block some countries
[[redirects]]
  from = "/*"
  to = "/451.html"
  status = 451
  force = true
  conditions = {Country=["BY","CU","IR","IQ","CI","LR","KP","SD","SY","ZW"]}
  headers = {Link="<https://uniswap.exchange>"}

# support SPA setup
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_CHAIN_ID = "4"
  REACT_APP_NETWORK_URL = "https://rinkeby.infura.io/v3/b8800ce81b8c451698081d269b86692b"
  REACT_APP_IS_PRODUCTION_DEPLOY = "false"

[context.production.environment]
  REACT_APP_IS_PRODUCTION_DEPLOY = "true"
