name: 'Chromatic'

on: push

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      # uses v1 to get full git history to track changes
      - uses: actions/checkout@af513c7a016048ae468971c52ed77d9562c7c819
      - name: Yarn Install
        uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
        with:
          timeout_minutes: 10
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --immutable
      - name: Publish to Chromatic
        uses: chromaui/action@c51a16ad99d38c810865c1e2dcecbd5bff508b3c
        with:
          buildScriptName: storybook:build
          # positive exit of action even when there are changes detected
          exitZeroOnChanges: true
          # skip waiting for build results
          exitOnceUploaded: true
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
