name: CI-Build-Test

on:
  workflow_call:

  # pull_request:
  #   types:
  #     - opened
  #     - synchronize
  #     - reopened
  #   paths:
  #     - 'apps/**'
  #     - 'packages/**'
  #     - 'package.json'
  #     - '*.lock'
  #     - '.yarnrc.yml'
  #     - '.prettier*'
  #     - '.github/**'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Set Node.js 18.14.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.14.0

      - name: ğŸ“¥ Monorepo install
        uses: ./.github/actions/yarn-install

      - name: ğŸ•µï¸ Typecheck
        run: yarn g:typecheck

      - name: ğŸ”¬ Lint
        run: yarn g:lint

      - name: ğŸ“ Format check
        run: yarn g:format:check

      - name: ğŸ— Build
        run: yarn g:build

      - name: ğŸ§ª Unit tests
        run: yarn g:test
