name: '[mobile] E2E Testing (iOS)'
# referenced from https://github.com/invertase/react-native-firebase/blob/master/.github/workflows/tests_e2e_ios.yml

on:
  workflow_dispatch:

jobs:
  ios:
    name: iOS
    runs-on: macos-11
    timeout-minutes: 75
    steps:
      - uses: styfle/cancel-workflow-action@860d4c7374d6e4a1c482e80897cb913ae46692ac
        with:
          all_but_latest: true

      # Set up tool versions
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: 18

      - uses: maxim-lobanov/setup-xcode@4aa4176a819ae7c019451acfda0bba67bffc6704
        with:
          xcode-version: '13.0'

      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
        with:
          fetch-depth: 50

      # Set path variables needed for caches
      - name: Set workflow variables
        id: workflow-variables
        run: |
          echo "::set-output name=metro-cache::$HOME/.metro"
          echo "::set-output name=xcode-version::$(xcodebuild -version|tail -1|cut -f3 -d' ')"

      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        name: Detox Framework Cache
        id: detox-cache
        with:
          path: ~/Library/Detox/ios
          key: ${{ runner.os }}-detox-framework-cache-${{ steps.workflow-variables.outputs.xcode-version }}

      # Detox is compiled during yarn install, using Xcode, set up cache first
      - uses: hendrikmuhs/ccache-action@ed038da2f2f09b0c8387c00e1498290a4808da2e
        name: Xcode Compile Cache
        with:
          key: ${{ runner.os }}-v2 # makes a unique key w/related restore key internally
          max-size: 400M

      - name: ðŸ“¥ Install
        uses: ./.github/actions/monorepo_yarn_install

      - name: ðŸ’Ž Update Ruby build tools
        uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
        with:
          timeout_minutes: 2
          retry_wait_seconds: 60
          max_attempts: 3
          command: gem update cocoapods xcodeproj

      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        name: ðŸ“€ Cache Pods
        id: pods-cache
        with:
          path: tests/ios/Pods
          key: ${{ runner.os }}-pods-v2-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-v2

      - name: ðŸ«› Pod Install
        uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
        working-directory: ./apps/mobile/ios
        with:
          timeout_minutes: 10
          retry_wait_seconds: 30
          max_attempts: 3
          command: pod install

      - name: ðŸŽ Build iOS App
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          export CCACHE_SLOPPINESS=clang_index_store,file_stat_matches,include_file_ctime,include_file_mtime,ivfsoverlay,pch_defines,modules,system_headers,time_macros
          export CCACHE_FILECLONE=true
          export CCACHE_DEPEND=true
          export CCACHE_INODECACHE=true
          ccache -s
          export SKIP_BUNDLING=1
          export RCT_NO_LAUNCH_PACKAGER=1
          set -o pipefail
          RN_SRC_EXT=e2e.js yarn detox build e2e -c ios.sim.debug
          ccache -s
        shell: bash

      - name: Install applesimutils
        uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 3
          command: HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew && HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils && applesimutils --list

      - name: Metro Bundler Cache
        uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        with:
          path: ${{ steps.workflow-variables.outputs.metro-cache }}
          key: ${{ runner.os }}-metro-v1-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-metro-v1

      - name: Pre-fetch Javascript bundle
        run: |
          nohup yarn test:e2e:packager &
          printf 'Waiting for packager to come online'
          until curl --output /dev/null --silent --head --fail http://localhost:8081/status; do
            printf '.'
            sleep 2
          done
          echo "Packager is online! Preparing bundle..."
          curl --output /dev/null --silent --head --fail "http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false&inlineSourceMap=true"
          echo "...javascript bundle ready"

      - name: Create Simulator Log
        # With a little delay so the detox test below has time to spawn it, missing the first part of boot is fine
        # If you boot the simulator separately from detox, some other race fails and detox testee never sends ready to proxy
        continue-on-error: true
        run: nohup sh -c "sleep 30 && xcrun simctl spawn booted log stream --style compact > simulator.log 2>&1 &"

      - name: Hardhat Fork Mainnet
        run: yarn hardhat &

      - name: Detox Test
        timeout-minutes: 60
        run: RN_SRC_EXT=e2e.js yarn detox test -c ios.sim.debug --cleanup --record-videos failing

      - name: Upload Detox Artifacts
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
        if: failure()
        with:
          name: artifacts
          path: artifacts
          if-no-files-found: ignore

      - name: Compress Simulator Log
        if: always()
        run: gzip -9 simulator.log

      - name: Upload Simulator Log
        uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2
        if: always()
        with:
          name: simulator_log
          path: simulator.log.gz
