name: '[mobile] Testing'

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  jest:
    name: Jest
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@860d4c7374d6e4a1c482e80897cb913ae46692ac
        with:
          all_but_latest: true
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
        with:
          fetch-depth: 50
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: 16
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@937d24475381cd9c75ae6db12cb4e79714b926ed
        name: Yarn Cache
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-v1-${{ hashFiles('**/package.json') }}
          restore-keys: ${{ runner.os }}-yarn-v1
      - name: Yarn Install
        uses: nick-fields/retry@7d4a37704547a311dbb66ebdf5b23ec19374a767
        with:
          timeout_minutes: 5
          retry_wait_seconds: 60
          max_attempts: 3
          command: yarn --immutable && cd apps/mobile && yarn --immutable
      - name: Typechain
        run: yarn mobile contracts:compile
      - name: Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      - name: Jest
        run: yarn mobile test --collectCoverage=true --max-workers=${{ steps.cpu-cores.outputs.count }}
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
      - name: Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
