name: '[mobile] Code Quality Checks'
# https://github.com/invertase/react-native-firebase/blob/master/.github/workflows/linting.yml

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main

jobs:
  jest:
    name: Run Unit Tests
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@860d4c7374d6e4a1c482e80897cb913ae46692ac
        with:
          all_but_latest: true
        
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
        with:
          fetch-depth: 50
      
      - name: ğŸ“¥ Install
        uses: ./.github/actions/monorepo_yarn_install
      
      - name: ğŸ›ï¸ Get number of CPU cores
        id: cpu-cores
        uses: SimenB/github-actions-cpu-cores@v1
      
      - name: ğŸ§ª Jest
        run: yarn mobile test --collectCoverage=true --max-workers=${{ steps.cpu-cores.outputs.count }}

      - name: ğŸ«¢ Upload coverage to Codecov
        uses: codecov/codecov-action@d9f34f8cd5cb3b3eb79b3e4b5dae3a16df499a70
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

      - name: âš ï¸  Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
