name: '[monorepo] Integrity'

on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - main
      - interface

jobs:
  monorepo-integrity:
    name: Check integrity
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
        with:
          fetch-depth: 2

      - name: ğŸ“¥ Install
        uses: ./.github/actions/monorepo_yarn_install

      - name: ğŸ‘¬ğŸ½ Check for conflicting versions across the monorepo
        run: yarn g:check:deps

      - name: ğŸ‘¬ğŸ½ Check for circular imports across the monorepo
        run: yarn g:check:circular

      - name: ğŸ‘¬ğŸ½ Check for duplicate dependencies in lock file
        run: yarn dedupe --check

      - name: ğŸ§‘â€âš–ï¸ Check for yarn constraints.pro
        run: yarn constraints
