name: "Tag and release"
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: ğŸ§·ï¸ Get version
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        id: version
        with:
          path: VERSION

      - name: ğŸ§¾ï¸ Get release notes
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        id: release-notes
        with:
          path: RELEASE

      - name: ğŸ·ï¸ Tag
        id: github-tag-action
        uses: uniswap/github-tag-action@7bddacd4864a0f5671e836721db60174d8a9c399
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.content }}
          tag_prefix: ""

      - name: ğŸª½ Release
        uses: actions/create-release@8e3b4a5e184b498423d5b25ca5ceb5a9258c92c2
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Or use your PAT
        with:
          tag_name: ${{ steps.github-tag-action.outputs.new_tag }}
          release_name: Release ${{ steps.github-tag-action.outputs.new_tag }}
          body: ${{ steps.release-notes.outputs.content }}
